import React, { useState, useEffect } from "react"

import { BigNumber, utils } from "ethers"

import { useCollectableFees, useFeesBalance, useTotalFeesCollected } from "../../hooks/useGovernance"
import { fromDecimals, round } from "../../utils/formatter"
import { TitleValueBox } from "../TitleValueBox"

import { Token } from "../../types/Token"
import { Box, makeStyles, Typography, Card, CardContent, CardActions } from "@material-ui/core"
import { Horizontal } from "../Layout"

interface DAORevenuesProps {
    chainId: number,
    account?: string,
    depositToken: Token
}

const useStyles = makeStyles( theme => ({
    tokenInfo: {
        maxWidth: 600,
        margin: "auto"
    },
    container: {
        // textAlign: "center",
        padding: theme.spacing(2),
        minHeight: 300
    },
    info:{
        margin: "auto"
    }
}))


export const DAORevenues = ({ chainId, account, depositToken } : DAORevenuesProps ) => {

    const classes = useStyles()
    
    const collectableFees = useCollectableFees(chainId)
    const feesBalance = useFeesBalance(chainId)
    const totalFees = (collectableFees && feesBalance) ? collectableFees.add(feesBalance) : undefined


    const collectableFeesFormatted = collectableFees ? fromDecimals(collectableFees, depositToken.decimals, 2) : ""
    const feesBalanceFormatted = feesBalance ? fromDecimals(feesBalance, depositToken.decimals, 2) : ""
    const totalFeesFormatted = totalFees ? fromDecimals(totalFees, depositToken.decimals, 2) : ""


    console.log("DAORevenues - collectableFees", collectableFeesFormatted,  "feesBalance", feesBalanceFormatted, "totalFees >> ", totalFeesFormatted)


    return (
        <Box className={classes.container}>
            <Box p={0}>
                DAO revenues come from fees collected on profits generated by HashStrat Pools &amp; Indexes. <br/>
                Fees are currentrly set at 1% of profits withdrawn by users. <br/>
                <br/>
                In the future, HST token holders will be able to 
                adjust this percentage through the DAO governance and collect their share of of the DAO revenues.
            </Box>



            <Box my={4}>

                <Horizontal align="center">

                    <Card  style={{width: 220}}  >
                        <CardContent>
                                <div style={{ display:'flex', justifyContent:'center' }}> 
                                    <Typography variant="body1" style={{ marginBottom: 10 }} > Fees Collected </Typography>
                                </div>
                                <div style={{ display:'flex', justifyContent:'center' }}> 
                                    <Typography variant="h5" style={{ marginBottom: 10 }} >
                                        { utils.commify( totalFeesFormatted ) } { depositToken.symbol }
                                    </Typography>
                                </div>
                        </CardContent>
                    </Card>

                </Horizontal>

            </Box>
</Box>

    )
}


